# Generated by Django 3.1.4 on 2020-12-20 04:33

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutpage_about_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_about',
            field=wagtail.core.fields.StreamField([('Title', wagtail.core.blocks.CharBlock()), ('subtitle', wagtail.core.blocks.CharBlock()), ('profile_image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
    ]
