# Generated by Django 3.1.4 on 2020-12-20 04:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_blog', wagtail.core.fields.StreamField([('Title', wagtail.core.blocks.CharBlock()), ('subtitle', wagtail.core.blocks.CharBlock()), ('profile_image', wagtail.core.blocks.CharBlock())], blank=True, null=True)),
                ('featured_section', wagtail.core.fields.StreamField([('Featured_Articles', wagtail.core.blocks.StructBlock([('article_card_pictue', wagtail.images.blocks.ImageChooserBlock(blank=True, null=True, required=False)), ('article_card_author_pictue', wagtail.images.blocks.ImageChooserBlock(blank=True, null=True, required=False)), ('article_card_author_name', wagtail.core.blocks.CharBlock(blank=True, null=True, required=False)), ('article_card_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('article_card_description', wagtail.core.blocks.RichTextBlock(blank=True, max_lenght=500, null=True, required=True))]))], blank=True, help_text='5 articles', null=True)),
                ('popular_section', wagtail.core.fields.StreamField([('Popular_Articles', wagtail.core.blocks.StructBlock([('article_card_pictue', wagtail.images.blocks.ImageChooserBlock(blank=True, null=True, required=False)), ('article_card_author_pictue', wagtail.images.blocks.ImageChooserBlock(blank=True, null=True, required=False)), ('article_card_author_name', wagtail.core.blocks.CharBlock(blank=True, null=True, required=False)), ('article_card_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('article_card_description', wagtail.core.blocks.RichTextBlock(blank=True, max_lenght=500, null=True, required=True))]))], blank=True, help_text='ideally 6 articles', null=True)),
                ('latest_section', wagtail.core.fields.StreamField([('Latest_Articles', wagtail.core.blocks.StructBlock([('article_card_pictue', wagtail.images.blocks.ImageChooserBlock(blank=True, null=True, required=False)), ('article_card_author_pictue', wagtail.images.blocks.ImageChooserBlock(blank=True, null=True, required=False)), ('article_card_author_name', wagtail.core.blocks.CharBlock(blank=True, null=True, required=False)), ('article_card_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('article_card_description', wagtail.core.blocks.RichTextBlock(blank=True, max_lenght=500, null=True, required=True))]))], blank=True, help_text='ideally 6 articles', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
