# Generated by Django 3.1.4 on 2020-12-17 03:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='external_cta',
            field=wagtail.core.fields.StreamField([('external_link', wagtail.core.blocks.StructBlock([('external_link', wagtail.core.blocks.URLBlock(blank=True, null=True, required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_one',
            field=wagtail.core.fields.StreamField([('Title_and_Text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False)), ('subtitle', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='signup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
