# Generated by Django 3.1.4 on 2020-12-17 04:32

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201217_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='customer_help_cta',
            field=wagtail.core.fields.StreamField([('offering_cta', wagtail.core.blocks.StructBlock([('top_title', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False)), ('title', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False)), ('subtitle', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False))])), ('offering_action', wagtail.core.blocks.StructBlock([('external_link', wagtail.core.blocks.URLBlock(blank=True, null=True, required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='customer_service_stats',
            field=wagtail.core.fields.StreamField([('statistics', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False)), ('subtitle', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='my_services',
            field=wagtail.core.fields.StreamField([('section_title', wagtail.core.blocks.StructBlock([('top_title', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False)), ('title', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False)), ('subtitle', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False))])), ('icon_title_subtitle', wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False)), ('title', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False)), ('subtitle', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False))])), ('personal_service_button', wagtail.core.blocks.StructBlock([('external_link', wagtail.core.blocks.URLBlock(blank=True, null=True, required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offering_cta',
            field=wagtail.core.fields.StreamField([('offering_cta', wagtail.core.blocks.StructBlock([('top_title', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False)), ('title', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False)), ('subtitle', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False))])), ('offering_action', wagtail.core.blocks.StructBlock([('external_link', wagtail.core.blocks.URLBlock(blank=True, null=True, required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team_detail',
            field=wagtail.core.fields.StreamField([('offering_cta', wagtail.core.blocks.StructBlock([('top_title', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False)), ('title', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False)), ('subtitle', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False))])), ('offering_action', wagtail.core.blocks.StructBlock([('external_link', wagtail.core.blocks.URLBlock(blank=True, null=True, required=True))]))], blank=True, null=True),
        ),
    ]
