# Generated by Django 3.1.4 on 2020-12-17 05:10

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201217_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='customer_help_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='customer_service_stats',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='external_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='login',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='my_services',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='offering_cta',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='signup',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_one',
            field=wagtail.core.fields.StreamField([('hero_one_cta', wagtail.core.blocks.StructBlock([]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='team_detail',
            field=wagtail.core.fields.StreamField([('team_card', wagtail.core.blocks.StructBlock([('profile_pic', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('profile_pic', wagtail.images.blocks.ImageChooserBlock(required=True)), ('name', wagtail.core.blocks.CharBlock(blank=True, null=True, required=True)), ('tagline', wagtail.core.blocks.CharBlock(blank=True, null=True, required=True)), ('number_of_jobs', wagtail.core.blocks.IntegerBlock(blank=True, null=True, required=True)), ('skill_tags', wagtail.core.blocks.StructBlock([('skill_tag', wagtail.core.blocks.CharBlock(blank=True, null=True, required=True))])), ('more_detail', wagtail.core.blocks.URLBlock(blank=True, null=True, required=True))])))]))], blank=True, null=True),
        ),
    ]
