# Generated by Django 3.1.4 on 2020-12-17 05:16

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201217_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_one',
            field=wagtail.core.fields.StreamField([('hero_one_cta', wagtail.core.blocks.StructBlock([('hero_one', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('login', wagtail.core.blocks.PageChooserBlock()), ('signup', wagtail.core.blocks.PageChooserBlock()), ('Title_and_Text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False)), ('subtitle', wagtail.core.blocks.CharBlock(blank=True, max_length=500, null=True, required=False))]))])))]))], blank=True, null=True),
        ),
    ]
