# Generated by Django 3.1.4 on 2020-12-17 05:33

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20201217_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_one',
            field=wagtail.core.fields.StreamField([('login', wagtail.core.blocks.PageChooserBlock()), ('signup', wagtail.core.blocks.PageChooserBlock()), ('Title', wagtail.core.blocks.CharBlock()), ('subtitle', wagtail.core.blocks.CharBlock())], blank=True, null=True),
        ),
    ]
