# Generated by Django 3.1.4 on 2020-12-17 05:56

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201217_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='my_services',
            field=wagtail.core.fields.StreamField([('section_top_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('section_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('section_bottom_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('icon_title_subtitle', wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(required=False)), ('service_type', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('hours_of_experience', wagtail.core.blocks.IntegerBlock(default=0))])), ('personal_service_button', wagtail.core.blocks.PageChooserBlock(blank=True, null=True, required=True))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='team_detail',
            field=wagtail.core.fields.StreamField([('member_card', wagtail.core.blocks.StructBlock([('profile_pic', wagtail.images.blocks.ImageChooserBlock(required=True)), ('name', wagtail.core.blocks.CharBlock(blank=True, null=True, required=True)), ('tagline', wagtail.core.blocks.CharBlock(blank=True, null=True, required=True)), ('number_of_jobs', wagtail.core.blocks.IntegerBlock(blank=True, null=True, required=True)), ('skill_tags', wagtail.core.blocks.StructBlock([('skill_tag', wagtail.core.blocks.CharBlock(blank=True, null=True, required=True))])), ('more_detail', wagtail.core.blocks.PageChooserBlock(blank=True, null=True, required=True))]))], blank=True, null=True),
        ),
    ]
