# Generated by Django 3.1.4 on 2020-12-17 06:08

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201217_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='customer_service_stats',
            field=wagtail.core.fields.StreamField([('statistic', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('value', wagtail.core.blocks.IntegerBlock())]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offering_cta',
            field=wagtail.core.fields.StreamField([('offering_detail', wagtail.core.blocks.StructBlock([('section_top_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('section_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('section_description', wagtail.core.blocks.RichTextBlock(blank=True, null=True, required=True))])), ('offering_action', wagtail.core.blocks.PageChooserBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='my_services',
            field=wagtail.core.fields.StreamField([('section_heading', wagtail.core.blocks.StructBlock([('section_top_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('section_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('section_bottom_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True))])), ('service_card', wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(required=False)), ('service_type', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('hours_of_experience', wagtail.core.blocks.IntegerBlock(default=0))])), ('personal_service_button', wagtail.core.blocks.PageChooserBlock(blank=True, null=True, required=True))], blank=True, null=True),
        ),
    ]
