# Generated by Django 3.1.4 on 2020-12-17 06:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20201217_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='features_list',
            field=wagtail.core.fields.StreamField([('offering_cta', wagtail.core.blocks.StructBlock([('Feature_icon', wagtail.images.blocks.ImageChooserBlock(blank=True, null=True, required=False)), ('Feature_Title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('Feature_Text', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hire_cta',
            field=wagtail.core.fields.StreamField([('offering_detail', wagtail.core.blocks.StructBlock([('section_top_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('section_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('section_description', wagtail.core.blocks.RichTextBlock(blank=True, null=True, required=True))])), ('offering_action', wagtail.core.blocks.PageChooserBlock())], blank=True, null=True),
        ),
    ]
