# Generated by Django 3.1.4 on 2020-12-17 06:44

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20201217_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='final_hire_cta',
            field=wagtail.core.fields.StreamField([('offering_detail', wagtail.core.blocks.StructBlock([('section_top_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('section_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('section_description', wagtail.core.blocks.RichTextBlock(blank=True, null=True, required=True))])), ('offering_action', wagtail.core.blocks.PageChooserBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('link_group', wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.PageChooserBlock())]))], blank=True, null=True),
        ),
    ]
