# Generated by Django 3.1.4 on 2020-12-20 03:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20201217_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='footer',
            field=wagtail.core.fields.StreamField([('link_group', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('links', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.PageChooserBlock())])))]))), ('Terms_of_service', wagtail.core.blocks.PageChooserBlock()), ('Privacy_Policy', wagtail.core.blocks.PageChooserBlock()), ('Copy_Right_Owner', wagtail.core.blocks.PageChooserBlock()), ('Login', wagtail.core.blocks.PageChooserBlock()), ('Sign_Up', wagtail.core.blocks.PageChooserBlock())], blank=True, null=True),
        ),
    ]
