# Generated by Django 3.1.4 on 2020-12-25 08:04

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='customer_service_stats',
            field=wagtail.core.fields.StreamField([('statistic', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('value', wagtail.core.blocks.IntegerBlock())]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_list',
            field=wagtail.core.fields.StreamField([('offering_cta', wagtail.core.blocks.StructBlock([('Feature_icon', wagtail.images.blocks.ImageChooserBlock(blank=True, null=True, required=False)), ('Feature_Title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('Feature_Text', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='final_hire_cta',
            field=wagtail.core.fields.StreamField([('offering_detail', wagtail.core.blocks.StructBlock([('section_top_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('section_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('section_description', wagtail.core.blocks.RichTextBlock(blank=True, null=True, required=True))])), ('offering_action', wagtail.core.blocks.PageChooserBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer',
            field=wagtail.core.fields.StreamField([('link_group', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('links', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('link', wagtail.core.blocks.PageChooserBlock())])))]))), ('Terms_of_service', wagtail.core.blocks.PageChooserBlock()), ('Privacy_Policy', wagtail.core.blocks.PageChooserBlock()), ('Copy_Right_Owner', wagtail.core.blocks.PageChooserBlock()), ('Login', wagtail.core.blocks.PageChooserBlock()), ('Sign_Up', wagtail.core.blocks.PageChooserBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_one',
            field=wagtail.core.fields.StreamField([('login', wagtail.core.blocks.PageChooserBlock()), ('signup', wagtail.core.blocks.PageChooserBlock()), ('Title', wagtail.core.blocks.CharBlock()), ('subtitle', wagtail.core.blocks.CharBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hire_cta',
            field=wagtail.core.fields.StreamField([('offering_detail', wagtail.core.blocks.StructBlock([('section_top_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('section_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('section_description', wagtail.core.blocks.RichTextBlock(blank=True, null=True, required=True))])), ('offering_action', wagtail.core.blocks.PageChooserBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='my_services',
            field=wagtail.core.fields.StreamField([('section_heading', wagtail.core.blocks.StructBlock([('section_top_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('section_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('section_bottom_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True))])), ('service_card', wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock(required=False)), ('service_type', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('hours_of_experience', wagtail.core.blocks.IntegerBlock(default=0))])), ('personal_service_button', wagtail.core.blocks.PageChooserBlock(blank=True, null=True, required=True))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offering_cta',
            field=wagtail.core.fields.StreamField([('offering_detail', wagtail.core.blocks.StructBlock([('section_top_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('section_title', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True)), ('section_description', wagtail.core.blocks.RichTextBlock(blank=True, null=True, required=True))])), ('offering_action', wagtail.core.blocks.PageChooserBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team_detail',
            field=wagtail.core.fields.StreamField([('member_card', wagtail.core.blocks.StructBlock([('profile_pic', wagtail.images.blocks.ImageChooserBlock(required=True)), ('name', wagtail.core.blocks.CharBlock(blank=True, null=True, required=True)), ('tagline', wagtail.core.blocks.CharBlock(blank=True, null=True, required=True)), ('number_of_jobs', wagtail.core.blocks.IntegerBlock(blank=True, null=True, required=True)), ('skill_tags', wagtail.core.blocks.StructBlock([('skill_tag', wagtail.core.blocks.CharBlock(blank=True, null=True, required=True))])), ('more_detail', wagtail.core.blocks.PageChooserBlock(blank=True, null=True, required=True))]))], blank=True, null=True),
        ),
    ]
