# Generated by Django 3.1.4 on 2020-12-25 07:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='contact_Block',
            field=wagtail.core.fields.StreamField([('contact_section', wagtail.core.blocks.StructBlock([('contact_type', wagtail.core.blocks.CharBlock(blank=True, null=True, required=False)), ('contact_detail', wagtail.core.blocks.CharBlock(blank=True, max_lenght=500, null=True, required=True))], black=True, null=True))], null=True),
        ),
    ]
